(function(root){
'use strict';
const formats={wav:{mime:'audio/wav',args:['-c:a','pcm_s16le']},mp3:{mime:'audio/mpeg',args:['-c:a','libmp3lame']},flac:{mime:'audio/flac',args:['-c:a','flac']},m4a:{mime:'audio/mp4',args:['-c:a','aac','-movflags','+faststart']},aac:{mime:'audio/aac',args:['-c:a','aac','-f','adts']},ogg:{mime:'audio/ogg',args:['-c:a','libvorbis']},opus:{mime:'audio/ogg',args:['-c:a','libopus','-ar','48000']},webm:{mime:'audio/webm',args:['-c:a','libopus','-ar','48000']}};
function codecArgs(format,bitrate=192){const f=formats[format];if(!f)throw Error('不支持的音频格式');if(![64,96,128,192,256,320].includes(Number(bitrate)))throw Error('无效的音频码率');return [...f.args,...(['wav','flac'].includes(format)?[]:['-b:a',`${bitrate}k`])];}
async function encode(ff,wav,format,bitrate){const args=codecArgs(format,bitrate),input='audio_input.wav',output=`audio_output.${format}`;try{await ff.writeFile(input,new Uint8Array(wav));const code=await ff.exec(['-hide_banner','-loglevel','error','-y','-i',input,'-vn',...args,output]);if(code!==0)throw Error(`音频转换失败（code ${code}）`);const bytes=await ff.readFile(output);if(!(bytes instanceof Uint8Array)||!bytes.length)throw Error('没有生成有效的音频文件');return new Blob([bytes],{type:formats[format].mime});}finally{for(const file of [input,output])try{await ff.deleteFile(file);}catch{}}}
function create(){let ff,promise,generation=0,progress=()=>{};async function get(){if(ff)return ff;if(promise)return promise;const current=generation;promise=(async()=>{const [m,u]=await Promise.all([import('https://esm.sh/@ffmpeg/ffmpeg@0.12.15'),import('https://esm.sh/@ffmpeg/util@0.12.2')]);if(current!==generation)throw Error('导出已取消');const instance=new m.FFmpeg();ff=instance;instance.on('progress',({progress:p})=>progress(Math.max(0,Math.min(100,p*100))));const base='https://unpkg.com/@ffmpeg/core@0.12.10/dist/esm';await instance.load({classWorkerURL:new URL('./ffmpeg-worker.js',location.href).href,coreURL:await u.toBlobURL(`${base}/ffmpeg-core.js`,'text/javascript'),wasmURL:await u.toBlobURL(`${base}/ffmpeg-core.wasm`,'application/wasm')});if(current!==generation)throw Error('导出已取消');return instance;})().catch(e=>{ff?.terminate();ff=null;throw e;});try{return await promise;}finally{promise=null;}}
return {async convert(wav,format,bitrate,onProgress=()=>{}){progress=onProgress;const engine=await get();return encode(engine,wav,format,bitrate);},cancel(){generation++;ff?.terminate();ff=null;promise=null;}};}
const api={formats,codecArgs,encode,create};if(typeof module==='object')module.exports=api;else root.AudioExport=api;
})(globalThis);
