(function(root){
'use strict';
function fft(re,im){const n=re.length;for(let i=1,j=0;i<n;i++){let bit=n>>1;for(;j&bit;bit>>=1)j^=bit;j^=bit;if(i<j){[re[i],re[j]]=[re[j],re[i]];[im[i],im[j]]=[im[j],im[i]];}}for(let len=2;len<=n;len*=2){const a=-2*Math.PI/len;for(let i=0;i<n;i+=len){let wr=1,wi=0;for(let j=0;j<len/2;j++){const k=i+j,l=k+len/2,tr=wr*re[l]-wi*im[l],ti=wr*im[l]+wi*re[l];re[l]=re[k]-tr;im[l]=im[k]-ti;re[k]+=tr;im[k]+=ti;const next=wr*Math.cos(a)-wi*Math.sin(a);wi=wr*Math.sin(a)+wi*Math.cos(a);wr=next;}}}return re;}
function spectrum(samples,start,n){const re=new Float64Array(n),im=new Float64Array(n);for(let i=0;i<n;i++)re[i]=(samples[start+i]||0)*(.5-.5*Math.cos(2*Math.PI*i/(n-1)));fft(re,im);return Float32Array.from(re.slice(0,n/2),(_,i)=>20*Math.log10(Math.max(1e-8,Math.hypot(re[i],im[i])*4/n)));}
function mel(db,rate,n,bands=64){const max=2595*Math.log10(1+rate/1400),edges=Array.from({length:bands+2},(_,i)=>700*(10**(max*i/(bands+1)/2595)-1)*n/rate);return Float32Array.from({length:bands},(_,b)=>{let energy=0,weight=0;for(let k=Math.ceil(edges[b]);k<Math.min(db.length,edges[b+2]);k++){const w=k<edges[b+1]?(k-edges[b])/(edges[b+1]-edges[b]):(edges[b+2]-k)/(edges[b+2]-edges[b+1]);energy+=10**(db[k]/10)*w;weight+=w;}return 10*Math.log10(Math.max(1e-12,energy/Math.max(weight,1)));});}
function cepstrum(db){const n=db.length*2,re=new Float64Array(n),im=new Float64Array(n);for(let i=0;i<db.length;i++)re[i]=db[i]/20*Math.LN10;for(let i=1;i<db.length;i++)re[n-i]=re[i];fft(re,im);return Float32Array.from(re.slice(1,Math.min(n/2,512)),v=>v/n);}
function processAudio(channels,rate,options){const begin=Math.max(0,Math.round(options.start*rate)),end=Math.min(channels[0].length,Math.round(options.end*rate));if(end<=begin)throw Error('请选择有效的音频区间');const out=channels.map(c=>c.slice(begin,end));let peak=0;out.forEach(c=>{for(const v of c)peak=Math.max(peak,Math.abs(v));});const gain=10**(options.gain/20)*(options.normalize&&peak?0.98/peak:1);out.forEach(c=>{if(options.reverse)c.reverse();for(let i=0;i<c.length;i++){const fadeIn=options.fadeIn*rate,fadeOut=options.fadeOut*rate;const envelope=Math.min(1,fadeIn?i/fadeIn:1,fadeOut?(c.length-1-i)/fadeOut:1);c[i]=Math.max(-1,Math.min(1,c[i]*gain*Math.max(0,envelope)));}});return out;}
function wav(channels,rate){const length=channels[0].length,bytes=length*channels.length*2;if(bytes>0xffffffff-36)throw Error('音频超过 WAV 文件大小上限');const buffer=new ArrayBuffer(44+bytes),v=new DataView(buffer);function str(p,s){for(let i=0;i<s.length;i++)v.setUint8(p+i,s.charCodeAt(i));}str(0,'RIFF');v.setUint32(4,36+bytes,true);str(8,'WAVE');str(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,channels.length,true);v.setUint32(24,rate,true);v.setUint32(28,rate*channels.length*2,true);v.setUint16(32,channels.length*2,true);v.setUint16(34,16,true);str(36,'data');v.setUint32(40,bytes,true);let p=44;for(let i=0;i<length;i++)for(const c of channels){const x=Math.max(-1,Math.min(1,c[i]));v.setInt16(p,x<0?x*32768:x*32767,true);p+=2;}return buffer;}
const api={fft,spectrum,mel,cepstrum,processAudio,wav};if(typeof module==='object')module.exports=api;else root.AudioDSP=api;
})(typeof self!=='undefined'?self:globalThis);
